export default {
  namespaced: true,
  actions: {},
  mutations: {},
  state: {
    // 各个情景下气泡式图表
    bubbleChart: {},
    // 沉浸式图表
    immersionChart: [
      {
        id: "Equipment001",
        center: {
          longitude: 120.727427,
          latitude: 27.975672,
          height: 40
        },
        show: true,
        componentName: "EquipmentVue",
        anchor: [0, 0],
        width: 150,
        height: 100,
        rotate: 320,
        name: "排风机",
      },
      {
        id: "EquipmentClose",
        center: {
          longitude: 120.727362,
          latitude: 27.975624,
          height: 45.5
        },
        show: true,
        componentName: "EquipmentClose",
        anchor: [0, 0],
        width: 12,
        height: 12,
        rotate: 320,
        name: "排风机关闭按钮",
      },
      {
        id: "CarDetail001",
        center: {
          longitude: 120.726359,
          latitude: 27.976237,
          height: 20,
        },
        show: false,
        componentName: "CarDetailVue",
        anchor: [0, 0],
        width: 140,
        height: 90,
        rotate: 410,
        name: "车辆信息",
      },
      // {
      //   id: "parkEventDetail1",
      //   center: {
      //     longitude: 120.726362,
      //     latitude: 27.976237,
      //     height: 27,
      //   },
      //   show: true,
      //   componentName: "ParkEventDetail",
      //   anchor: [0, 0],
      //   width: 140,
      //   height: 90,
      //   rotate: 410,
      //   name: "监控信息",
      // },
      {
        id: "parkAllList1",
        center: {
          longitude: 120.726189,
          latitude: 27.976237,
          height: 30,
        },
        show: false,
        componentName: "ParkAllList",
        anchor: [0, 0],
        width: 170,
        height: 80,
        rotate: 410,
        name: "停车场信息",
      },
      // {
      //   id: "MeetingCamera001",
      //   center: {
      //     longitude: 120.726359,
      //     latitude: 27.976237,
      //     height: 20,
      //   },
      //   show: true,
      //   componentName: "MeetingCameraVue",
      //   anchor: [0, 0],
      //   width: 100,
      //   height: 100,
      //   rotate: 410,
      //   name: "会议室数量统计",
      // },
      {
        id: "roadCondition001",
        center: {
          longitude: 120.726909,
          latitude: 27.975977,
          height: 17,
        },
        show: true,
        componentName: "roadConditionVue",
        anchor: [0, 0],
        width: 130,
        height: 130,
        rotate: 380,
        name: "路况统计",
      },
      {
        id: "RoadConditionClose",
        center: {
          longitude: 120.726849,
          latitude: 27.975999,
          height: 24,
        },
        show: true,
        componentName: "RoadConditionClose",
        anchor: [0, 0],
        width: 20,
        height: 20,
        rotate: 380,
        name: "路况关闭按钮",
      },
      // {
      //   id: "EastGate",
      //   center: {
      //     longitude: 120.736909,
      //     latitude: 27.975977,
      //     height: 14,
      //   },
      //   show: true,
      //   componentName: "EastGateVue",
      //   anchor: [0, 0],
      //   width: 130,
      //   height: 130,
      //   rotate: 380,
      //   name: "东门",
      // },
      // {
      //   id: "EnterpriseListClose",
      //   center: {
      //     longitude: 120.726121,
      //     latitude: 27.975668,
      //     height: 51.5
      //   },
      //   show: true,
      //   componentName: "EnterpriseListCloseVue",
      //   anchor: [0, 0],
      //   width: 12,
      //   height: 12,
      //   rotate: 460,
      //   name: "企业展示关闭按钮",
      // },
      {
        id: "EnterpriseDetailClose",
        center: {
          longitude: 120.726152,
          latitude: 27.975827,
          height: 49.5
        },
        show: true,
        componentName: "EnterpriseDetailCloseVue",
        anchor: [0, 0],
        width: 12,
        height: 12,
        rotate: 460,
        name: "企业详情关闭按钮",
      },
      // {
      //   id: "CarStatisticsClose",
      //   center: {
      //     longitude: 120.726445,
      //     latitude: 27.976136,
      //     height: 29.5
      //   },
      //   show: true,
      //   componentName: "CarStatisticsCloseVue",
      //   anchor: [0, 0],
      //   width: 12,
      //   height: 12,
      //   rotate: 420,
      //   name: "车辆统计关闭按钮",
      // },
      {
        id: "CarDetailClose",
        center: {
          longitude: 120.726311,
          latitude: 27.976291,
          height: 25
        },
        show: true,
        componentName: "CarDetailClose",
        anchor: [0, 0],
        width: 12,
        height: 12,
        rotate: 410,
        name: "车辆信息关闭按钮",
      },
      {
        id: "ParkAllListClose",
        center: {
          longitude: 120.726141,
          latitude: 27.976310,
          height: 34.5,
        },
        show: true,
        componentName: "ParkAllListClose",
        anchor: [0, 0],
        width: 12,
        height: 12,
        rotate: 410,
        name: "停车场信息关闭按钮",
      },
      {
        id: "CheckDXC",
        center: {
          longitude: 120.726118,
          latitude: 27.975636,
          height: 46.5
        },
        show: true,
        componentName: "CheckDXCVue",
        anchor: [0, 0],
        width: 15,
        height: 12,
        rotate: 460,
        name: "查看DXC",
      },
    ],
    // 复杂沉浸式图表  TODO
    complexImmersionChart: {},
  },
  getters: {},
};
